"""Security-focused, unpack-only 7z archive and compressed-stream access."""

from ._native import (
    Archive,
    ArchiveIoError,
    ArchiveResources,
    CancelledError,
    CancellationToken,
    ChecksumError,
    CompressedStream,
    Entry,
    FormatError,
    InternalError,
    LimitExceededError,
    Limits,
    MissingVolumeError,
    PasswordRequiredError,
    StreamInfo,
    Un7zError,
    UnsupportedFeatureError,
    UnsupportedMethodError,
    WrongPasswordOrCorruptError,
    open_bytes,
    open_path,
    open_stream_bytes,
    open_stream_path,
    open_volumes,
)

__version__ = "0.1.0"

__all__ = [
    "Archive",
    "ArchiveIoError",
    "ArchiveResources",
    "CancelledError",
    "CancellationToken",
    "ChecksumError",
    "CompressedStream",
    "Entry",
    "FormatError",
    "InternalError",
    "LimitExceededError",
    "Limits",
    "MissingVolumeError",
    "PasswordRequiredError",
    "StreamInfo",
    "Un7zError",
    "UnsupportedFeatureError",
    "UnsupportedMethodError",
    "WrongPasswordOrCorruptError",
    "open_bytes",
    "open_path",
    "open_stream_bytes",
    "open_stream_path",
    "open_volumes",
]
